### ISSUE TITLE
Question about data effectiveness

### ISSUE THREAD

**Issue by jokerwyt** [sir-lab/data-release#3]
Let's focus on private trace, function 10, the first 60s of day 0.

It has 6 instances, 4 cores per instance, and 17 invocations. Its average CPU usage is 0.37. (i.e. 37%) among all instances.

So I can calc the absolute average CPU usage of a single invocation:
4 cores/instance * 6 pods * 37% / 17 invocations = 0.52 cores, in a minute interval. 

But, the function delay is only 7ms. This is far away from 0.52 cores*minutes per invocation calculation.

Could you please explain why? Am I getting something wrong?

**Comment by jokerwyt** [comment]
Do you allow functions to run in the background even if there is no request? That's an approach only suitable for cooperative cloud but the paper does not mention it.

**Comment by ajoosen** [comment]
Hi,

Thank you for your question.

In the Private Trace, CPU and memory usage are both calculated at the pod level using Prometheus, meaning that metrics will be collected at a certain frequency while the pod is alive. 

There are two types of pod allocations. There are "on-demand" instances and "reserved" instances. Reserved instances are always on and always running the code for that function, regardless of the number of function requests received. If the current reserved function instances cannot handle incoming requests, the platform will generate more on-demand function instances. Since the process running the function code is always running in reserved instances, this contributes to the CPU usage, even when there is no request at that specific time.

For function 10, we can see that the number of function instances is 6 for almost the entire day, while the number of requests varies between 4 and 71 requests per minute. Although we do not have the exact information about whether these are on-demand or reserved instances, the fact that the number of instances remains the same suggests these are likely to be reserved instances.

Therefore, we do not recommend trying to calculate the CPU usage in terms of the function delay (execution time) of requests.

Other than that, ultimately the CPU usage of a function depends on its internal logic, and we have no information about the internal behaviour of particular functions.

**Comment by jokerwyt** [comment]
> Hi,
> 
> Thank you for your question.
> 
> In the Private Trace, CPU and memory usage are both calculated at the pod level using Prometheus, meaning that metrics will be collected at a certain frequency while the pod is alive.
> 
> There are two types of pod allocations. There are "on-demand" instances and "reserved" instances. Reserved instances are always on and always running the code for that function, regardless of the number of function requests received. If the current reserved function instances cannot handle incoming requests, the platform will generate more on-demand function instances. Since the process running the function code is always running in reserved instances, this contributes to the CPU usage, even when there is no request at that specific time.
> 
> For function 10, we can see that the number of function instances is 6 for almost the entire day, while the number of requests varies between 4 and 71 requests per minute. Although we do not have the exact information about whether these are on-demand or reserved instances, the fact that the number of instances remains the same suggests these are likely to be reserved instances.
> 
> Therefore, we do not recommend trying to calculate the CPU usage in terms of the function delay (execution time) of requests.
> 
> Other than that, ultimately the CPU usage of a function depends on its internal logic, and we have no information about the internal behaviour of particular functions.

Got it. Thanks for your reply and the nice dataset.
