### ISSUE TITLE
Clarification on Resource Usage and Prediction results

### ISSUE THREAD

**Issue by praith-dsg** [sir-lab/data-release#5]
Hi,

I'm currently looking into the dataset and accompanying paper, and have two questions about it.

1. The dataset and paper mention that CPU limit is normalized. In what way is it normalized? The unit is cores after all.

In example, I would like to calculate the number of Cores you need to allocate for a given function over all instances.
Based on the other discussion (https://github.com/sir-lab/data-release/issues/3), and how limits are usually seen in Serverless, I would simply multiply the CPU Limit with the number of Instances.
Is this correct?

2. The paper shows MAPE, RMSE and MAE, and highlights that these values are normalized. Can you clarify how they were normalized? 

In example, is a MAPE of 0.44 equal to 44% or 0.44%? 
Is a the MAE of 0.2 equal to 0.2 requests (per second?) or normalized?

Thanks!

**Comment by ajoosen** [comment]
Hi,

Thank you for your message.

1. Please look at [Huawei Private demo notebook](https://github.com/sir-lab/data-release/blob/main/src/demo_private.ipynb) where I have added some code to demonstrate how to compute the amount of resources used across all instances.
2. We normalized the time series (subtract mean and divide by standard deviation) before computing metrics such as MAPE, RMSE, MAE so that the performance of the model on different functions could be compared more easily. MAPE of 0.44 would be 44%. MAE of 0.2 does not mean 0.2 requests.

Hope that helps.

Artjom
